services:
  - type: web
    name: kraftveb
    runtime: python
    buildCommand: ""
    startCommand: gunicorn flask_ui.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11